[package]
name = "newsy"
version = "0.1.0"
authors = ["JeffreyRiggle <JeffreyRiggle@gmail.com>"]

[dependencies]
hyper = "^0.12"
hyper-tls = "^0.3.0"
http = "^0.1.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1.23"
